services:
    webjaros_symfony_log_reader.record_admin:
        class: WebJaros\SymfonyLogReaderBundle\Admin\RecordAdmin
        arguments: [~, WebJaros\SymfonyLogReaderBundle\Entity\Record, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Symfony Logs }
